/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PostId = IDL.Nat;
export const Post = IDL.Record({
  'title' : IDL.Text,
  'created' : IDL.Int,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'tags' : IDL.Vec(IDL.Text),
  'lastUpdated' : IDL.Int,
  'author' : IDL.Principal,
});
export const Draft = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deletePost' : IDL.Func([PostId], [], []),
  'getAllPosts' : IDL.Func([], [IDL.Opt(IDL.Vec(Post))], ['query']),
  'getBlogs' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getBlogsByMe' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getCallerDrafts' : IDL.Func([], [IDL.Vec(Draft)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getPostsByMe' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getTaggedPostIds' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(PostId))],
      ['query'],
    ),
  'getUntaggedPosts' : IDL.Func([], [IDL.Vec(PostId)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'publish' : IDL.Func([PostId], [], []),
  'removeDraft' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDraft' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'submitBlog' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'submitPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'unpublish' : IDL.Func([PostId], [], []),
  'updatePost' : IDL.Func(
      [PostId, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PostId = IDL.Nat;
  const Post = IDL.Record({
    'title' : IDL.Text,
    'created' : IDL.Int,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'tags' : IDL.Vec(IDL.Text),
    'lastUpdated' : IDL.Int,
    'author' : IDL.Principal,
  });
  const Draft = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deletePost' : IDL.Func([PostId], [], []),
    'getAllPosts' : IDL.Func([], [IDL.Opt(IDL.Vec(Post))], ['query']),
    'getBlogs' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getBlogsByMe' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getCallerDrafts' : IDL.Func([], [IDL.Vec(Draft)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getPostsByMe' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getTaggedPostIds' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(PostId))],
        ['query'],
      ),
    'getUntaggedPosts' : IDL.Func([], [IDL.Vec(PostId)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'publish' : IDL.Func([PostId], [], []),
    'removeDraft' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDraft' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'submitBlog' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'submitPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'unpublish' : IDL.Func([PostId], [], []),
    'updatePost' : IDL.Func(
        [PostId, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };