/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Draft {
  'title' : string,
  'content' : string,
  'tags' : Array<string>,
}
export interface Post {
  'title' : string,
  'created' : bigint,
  'content' : string,
  'isPublished' : boolean,
  'tags' : Array<string>,
  'lastUpdated' : bigint,
  'author' : Principal,
}
export type PostId = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deletePost' : ActorMethod<[PostId], undefined>,
  'getAllPosts' : ActorMethod<[], [] | [Array<Post>]>,
  'getBlogs' : ActorMethod<[], Array<Post>>,
  'getBlogsByMe' : ActorMethod<[], Array<Post>>,
  'getCallerDrafts' : ActorMethod<[], Array<Draft>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPosts' : ActorMethod<[], Array<Post>>,
  'getPostsByMe' : ActorMethod<[], Array<Post>>,
  'getTaggedPostIds' : ActorMethod<[string], [] | [Array<PostId>]>,
  'getUntaggedPosts' : ActorMethod<[], Array<PostId>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'publish' : ActorMethod<[PostId], undefined>,
  'removeDraft' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDraft' : ActorMethod<[string, string, Array<string>], undefined>,
  'submitBlog' : ActorMethod<[string, string, Array<string>], undefined>,
  'submitPost' : ActorMethod<[string, string, Array<string>], undefined>,
  'unpublish' : ActorMethod<[PostId], undefined>,
  'updatePost' : ActorMethod<
    [PostId, string, string, Array<string>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];